ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'VERIFICATION_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "ProviderStatus" ADD VALUE IF NOT EXISTS 'DRAFT';

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "mobile" TEXT,
  ADD COLUMN IF NOT EXISTS "profilePhotoUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "emailVerified" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "phoneVerified" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Provider"
  ADD COLUMN IF NOT EXISTS "profilePhotoUrl" TEXT,
  ALTER COLUMN "mobile" DROP NOT NULL,
  ALTER COLUMN "address" DROP NOT NULL,
  ALTER COLUMN "city" DROP NOT NULL,
  ALTER COLUMN "categoryId" DROP NOT NULL,
  ALTER COLUMN "experienceYears" DROP NOT NULL,
  ALTER COLUMN "languages" SET DEFAULT ARRAY[]::TEXT[],
  ALTER COLUMN "officeAddress" DROP NOT NULL,
  ALTER COLUMN "bio" DROP NOT NULL,
  ALTER COLUMN "status" SET DEFAULT 'DRAFT';

CREATE INDEX IF NOT EXISTS "User_mobile_idx" ON "User"("mobile");
